# GET Users
GET http://localhost:3000/api/users




###
# GET User BASED ON ID
GET http://localhost:3000/api/users/:userId

###
POST http://localhost:3000/api/users
Content-Type: application/json


{
  "username": "New User",
  "password": "password1",
  "confirm-password": "password1"
}
